services:
  datadog-agent:
    image: public.ecr.aws/datadog/agent
    pid: host
    cgroup: host
    environment:
      - DD_API_KEY=$DD_API_KEY
      - DD_HOSTNAME=$DD_HOSTNAME
      - DD_SITE=datadoghq.com
      - DD_OTLP_CONFIG_LOGS_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_OTLP_CONFIG_LOGS_ENABLED=true
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT=0.0.0.0:4318
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    ports:
      - 4317:4317
      - 4318:4318
  isitdownrightnow.workerservice:
    image: isitdownrightnow.workerservice
    environment:
      - NetworkOptions__ControllerIPAddress=$NetworkOptions__ControllerIPAddress
    build:
      context: .
      dockerfile: IsitDownRightNow.WorkerService/Dockerfile
